### PR TITLE
Added support for PHP 8.2 and dropped 7.4, 8.0 

### PR DESCRIPTION
**Pull request by bcremer**

### CODE REVIEW

**Comment by bcremer** [comment]
Pushed version bumps of `webmozart/assert` and `phpunit/phpunit` so the prefer-lowest PHP 8.2 build is also green.

**Comment by michaelpetri** [comment]
Good morning, thanks for the patch! Now 7.4 fails but since this version isn't used that much anymore i suggest to just drop it? 

*Edit:* Also 8.0

**Comment by bcremer** [comment]
Should I go ahead and drop PHP 7.4 and PHP 8.0 support? 
Sound OK for me.

**Comment by bcremer** [comment]
Not sure why a PHP 7.1 build is still started.

**Comment by michaelpetri** [comment]
Sorry, you have to delete the https://github.com/bcremer/typed-input/blob/allow-php82/.laminas-ci.json, i had to do an override for 7.4, totally forgot about it :facepalm:

**Review by michaelpetri — APPROVED** [review]

**Comment by michaelpetri** [comment]
Thank you, i created a release! :handshake:

**Pull request merged**
